#!/usr/bin/env zsh

# Make vim the default editor.
export EDITOR='nvim'

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}"

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X'

export PATH="/usr/local/sbin:$PATH"

export ZSH=$HOME/.oh-my-zsh

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
